config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  if Rails.env.development?
    get 'kitchen_sink', to: 'pages#kitchen_sink'
  end

  resources :rooms, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
  end

  namespace :user do
    resources :bookings, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date
  validate :unbooked_date_range
  validate :start_date_after_today

  def booked_dates
    (start_date..end_date).to_a
  end

  private

  def unbooked_date_range
    return if room.available_between?(start_date, end_date)

    errors.add(:end_date, "room is not available for the given date range")
  end


  private

  def start_date_after_today
    return if end_date.blank? || start_date.blank?

    if start_date < Date.today
      errors.add(:start_date, "must be after today")
    end
  end

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings
  belongs_to :user
  validates :name, :price, :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def booked_recent_dates
    bookings.where("end_date > '#{Date.today}'").map do |booking|
      booking.booked_dates
    end.flatten
  end

  def available_between?(start_date, end_date)
    bookings.where(
      ":picked_start_date < start_date AND end_date < :picked_end_date",
      picked_start_date: start_date,
      picked_end_date: end_date
    ).or(
      conflicting_bookings_on(start_date).or(conflicting_bookings_on(end_date))
    ).empty?
  end

  def conflicting_bookings_on(date)
    bookings.where("? BETWEEN start_date AND end_date ", date)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :rooms, through: :bookings
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:owner])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :kitchen_sink]

  def create
    @booking = Booking.new(booking_params)
    @room    = Room.find(params[:room_id])

    @booking.user = current_user
    @booking.room = @room

    if @booking.save
      flash[:notice] = "Your Green Pasture Awaits!"
      redirect_to user_bookings_path
    else
      render "rooms/show"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :kitchen_sink]

  def home
    # TODO: ask Caio how make this efficient
    @rooms = Room.all.sample(6)
  end

  def kitchen_sink
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
    @markers =
      [{
        lat: @room.latitude,
        lng: @room.longitude
      }]
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.photo_url = "https://images.unsplash.com/photo-1581543591520-afa01e4d7e7b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80"
    @room.user = current_user
    if @room.save
      flash[:alert] = "Your Room is Added!"
      redirect_to room_path(@room)
    else
      render :new
    end
  end

  def room_params
    params.require(:room).permit(:name, :price, :address)
  end
end

app/controllers/user/bookings_controller.rb
class User::BookingsController < ApplicationController
  def index
    @user_bookings = Booking.where(user: current_user)
    @owner_bookings = Booking.joins(:room).where(rooms: { user: current_user })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/booked.html.erb
<%= @rooms_bookings%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://img.icons8.com/color/48/000000/hearts.png">
    <title>WE CARE </title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "components/flashes" %>

    <%= render 'components/navbar' %>
    <%= yield %>
    <%= render 'components/footer' %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'components/banner' %>
<%= render 'components/featured-rooms' %>

app/views/pages/kitchen_sink.html.erb
<%= render 'components/navbar' %>
<%= render 'components/banner' %>
<%= render 'components/footer' %>
<%= render 'components/room-card' %>

app/views/rooms/index.html.erb
<div class="container">
  <h2>Rooms:</h2>
  <div class="row">
    <% @rooms.each do |room| %>
      <div class="col-md-4 card-no-hover">
      <%= link_to room_path(room) do %>
        <div class="room-card">
          <%= image_tag(room.photo_url.to_s) %>
          <div class="room-card-infos">
            <div>
              <h2><%= room.name %></h2>
              <p><%= room.address %></p>
            </div>
            <h2 class="room-card-pricing"><%= room.price %></h2>
            <img src="https://res.cloudinary.com/dhlgr04v3/image/upload/v1582668209/old-man_a6rfdi.jpg" class="room-card-user avatar-bordered" />
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container mt-3">
  <div class="row d-flex justify-content-around">
    <div class="col-sm-6 bg bg-white pt-3 pb-4 border border-dark">
      <h2>Create A Room</h2>
      <%= simple_form_for @room do |form| %>
        <%= form.input :name %>
        <%= form.input :address %>
        <%= form.input :price, :label => "Price per Night" %>
        <%= form.submit "Create Room", class: "btn btn-primary", id: "create-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-around">
    <div class="col-sm-12 col-lg-9 py-4 bg bg-white border border-dark mt-4">
      <div class="booking">
        <h2><%= @room.name %></h2>
        <div class="booking-flex">
          <div class="booking-pic" style="background-image: url('<%= @room.photo_url.to_s%>');"></div>
          <div
            id="map"
            class="booking-map"
            style="width: 100%;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          ></div>
        </div>
        <div class="booking-info">
             <p><%= @room.address %></p>
        <h3>$<%= @room.price %> per night</h3>

        <%= simple_form_for [@room, @booking], method: :post, url: room_bookings_path(@room.id) do |form| %>
          <%= form.input :start_date,
            as: :date,
            html5: true,
            input_html: {
              class: "flatpickr col-sm-12 col-md-6",
              data: {
                disabled: @room.booked_recent_dates
              }
            } %>

          <%= form.input :end_date,
            as: :date,
            html5: true,
            input_html: {
              class: "flatpickr col-sm-12 col-md-6",
              data: {
                disabled: @room.booked_recent_dates
              }
            } %>
          <%= form.submit "Create Booking", class: "btn btn-primary mb-3", id: "create-btn" %>



        <% end %>

        </div>
      </div>
  </div>
</div>

app/views/user/bookings/index.html.erb
<div class="container p-0">
  <%if current_user.owner == false %>
 <h2>My bookings</h2>
  <div class="row">
    <% @user_bookings.each do |booking| %>
      <%= render "components/booking-card", room: booking.room, booking: booking %>
    <% end %>
  </div>

<%else%>

    <h2>My Bookings: Owner</h2>
    <div class="row">
    <% @owner_bookings.each do |booking| %>
      <%= render "components/booking-card", room: booking.room, booking: booking%>
    <% end %>
  </div>
</div>
<%end%>